server:
  port : 8080
spring:
  application:
    name: inboxapp
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.90b6e0693f90f8d0
            client-secret: c39204303ab974ec7370e138962b3ff8ea1351fa

  data:
    cassandra:
      keyspace-name: main
      username: OmCbMZzcwkBCYcJlvNmyTAPN
      password: c0jw.WGEGXG62woxNRI,hOD+clC5h9cZ5sEoXfFT+Hh3p4k8M85UgGjSd0S.tPfcxkLgX9KJifpCgEYpZa3Fhrc96MM1Jci5CbacOg6Rfwz-DSLgy85wpu4G1TWszZbR
      schema-action: recreate-drop-unused
      request:
        timeout: 60s
      connection:
        connect-timeout: 60s
        init-query-timeout: 60s

astra:
  db:
    id: 949f485d-9941-4994-94aa-1eece76911aa-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:OmCbMZzcwkBCYcJlvNmyTAPN:30c8c676b49cdffb19484867b8c40be4f60ceb6f17391b16c795529f5f684900

datastax.astra:
  secure-connect-bundle: secure-connect-my-inbox-app.zip